// Generated by scraper/update.py, which .github/workflows/scrape.yaml runs daily.
// The last 3 terms on bannerweb, oldest first. The course data of a term is in
// data-<term>-v<dataVersion>.min.json; the version moves on whenever the data
// changes, so browsers never keep serving a stale copy.
const termConfig = [
    {term: '202503', dataVersion: 111},
    {term: '202601', dataVersion: 111},
    {term: '202602', dataVersion: 111}
];
