"""
Keeps the course data of the last three terms on bannerweb up to date.

Run it from anywhere, as .github/workflows/scrape.yaml does every day:

    python scraper/update.py

It reads the supported terms from js/terms.js, slides that window forward when
bannerweb has added a newer term, scrapes every term in the window and stores the
data of the ones that changed under the next version number, as
data-<term>-v<version>.min.json. When anything changed it rewrites js/terms.js and,
if GITHUB_OUTPUT is set, reports "changes", "version" and "summary" there.
"""
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Dict, List

sys.path.insert(0, str(Path(__file__).resolve().parent))

from scrape import SUcheduleCourseScraper, serialize  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
TERMS_JS = ROOT / 'js' / 'terms.js'
WINDOW_SIZE = 3
TERM_ENTRY = re.compile(r"\{term: '(\d{6})', dataVersion: (\d+)\}")
TERMS_JS_TEMPLATE = """\
// Generated by scraper/update.py, which .github/workflows/scrape.yaml runs daily.
// The last {size} terms on bannerweb, oldest first. The course data of a term is in
// data-<term>-v<dataVersion>.min.json; the version moves on whenever the data
// changes, so browsers never keep serving a stale copy.
const termConfig = [
{entries}
];
"""


def next_term(term: str) -> str:
    """The term after the given one: Fall -> Spring -> Summer -> next year's Fall."""
    year, season = int(term[:4]), int(term[4:])
    return f'{year}{season + 1:02d}' if season < 3 else f'{year + 1}01'


def read_terms() -> Dict[str, int]:
    """The supported terms and their data versions, oldest first."""
    return {term: int(version) for term, version in TERM_ENTRY.findall(TERMS_JS.read_text(encoding='utf-8'))}


def write_terms(terms: Dict[str, int]) -> None:
    entries = ',\n'.join(f"    {{term: '{term}', dataVersion: {version}}}" for term, version in terms.items())
    TERMS_JS.write_text(TERMS_JS_TEMPLATE.format(size=WINDOW_SIZE, entries=entries), encoding='utf-8')


def data_file(term: str, version: int) -> Path:
    return ROOT / f'data-{term}-v{version}.min.json'


def data_files(term: str = '*') -> List[Path]:
    return sorted(ROOT.glob(f'data-{term}-v*.min.json'))


def remove(path: Path) -> None:
    """Removes a file, through git when it is tracked so that the deletion is staged."""
    result = subprocess.run(['git', 'rm', '-q', '-f', '--', str(path.relative_to(ROOT))],
                            cwd=ROOT, capture_output=True)
    if result.returncode != 0 and path.exists():
        path.unlink()
    print(f'Removed {path.name}')


def scrape(term: str) -> dict:
    print(f'Scraping {term}...')
    data = SUcheduleCourseScraper(term=int(term)).scrape()
    print(f'{term}: {len(data["courses"])} courses')
    return data


def report(changes: bool, version: int, summary: str) -> None:
    lines = [f'changes={"true" if changes else "false"}', f'version={version}', f'summary={summary}']
    output = os.environ.get('GITHUB_OUTPUT')
    if output:
        with open(output, 'a', encoding='utf-8') as file:
            file.write('\n'.join(lines) + '\n')
    print('\n'.join(lines))


def main() -> int:
    terms = read_terms()
    if not terms:
        print(f'::error::No terms found in {TERMS_JS}')
        return 1

    next_version = max(terms.values()) + 1
    window = list(terms)
    scraped: Dict[str, dict] = {}

    # Slide the window forward past every newer term bannerweb has added since.
    print('::group::Looking for new terms')
    for _ in range(WINDOW_SIZE):
        candidate = next_term(window[-1])
        data = scrape(candidate)
        if not data['courses']:
            print(f'{candidate} is not on bannerweb yet.')
            break
        print(f'New term detected: {candidate}')
        scraped[candidate] = data
        window.append(candidate)
    added = window[len(terms):]
    dropped = window[:-WINDOW_SIZE]
    window = window[-WINDOW_SIZE:]
    print('::endgroup::')

    print('::group::Updating course data')
    updated: Dict[str, int] = {}
    changed: List[str] = []
    for term in window:
        data = scraped.get(term) or scrape(term)
        current = data_file(term, terms[term]) if term in terms else None

        # A term with no courses is a bannerweb hiccup, or an old term taken down;
        # either way the last known data is better than none.
        if not data['courses']:
            if current is not None and current.exists():
                print(f'::warning::{term}: no courses were scraped, keeping {current.name}.')
                updated[term] = terms[term]
                continue
            print(f'::error::{term}: no courses were scraped and there is no earlier data to keep.')
            return 1

        text = serialize(data)
        if current is not None and current.exists() and current.read_text(encoding='utf-8') == text:
            print(f'{term}: no changes.')
            updated[term] = terms[term]
            continue

        for stale in data_files(term):
            remove(stale)
        data_file(term, next_version).write_text(text, encoding='utf-8')
        print(f'{term}: updated to v{next_version}.')
        updated[term] = next_version
        changed.append(term)

    for path in data_files():
        if path.name.split('-')[1] not in window:
            remove(path)
    print('::endgroup::')

    if list(updated.items()) == list(terms.items()):
        print('No changes detected in the scraped data.')
        report(False, next_version - 1, 'No changes')
        return 0

    write_terms(updated)
    print(f'Updated {TERMS_JS.relative_to(ROOT)}')

    summary = ', '.join([f'{term} -> v{updated[term]}' for term in changed]
                        + [f'new term {term}' for term in added]
                        + [f'dropped {term}' for term in dropped])
    report(True, next_version, summary)
    return 0


if __name__ == '__main__':
    sys.exit(main())
